### ISSUE TITLE
multiple editor

### ISSUE THREAD

**Issue by johnlim5847** [thijsw/angular-medium-editor#1]
Hi thijsw, may i know is it possible to make multiple editors in a same page ? i have tried it but it has some bugs when copy and paste content, the content will get multiply 
<div id="container" ng-controller="ComposeCtrl">
    <div ng-model="post.title" data-placeholder="Title" medium-editor data-disable-toolbar="true"></div>
    <div ng-model="post.preview"  data-placeholder="Preview" medium-editor data-disable-toolbar="true"></div>
    <div ng-model="post.content" medium-editor></div>
</div>

**Comment by AlexandreKilian** [comment]
this should be close, i have multiple editors (maximum was about 30 editors, don't ask) and it works just fine...

**Comment by thijsw** [comment]
WIll close as it seems to work just fine
