### ISSUE TITLE
calling onChange on input causes sluggish typing...

### ISSUE THREAD

**Issue by michelob** [thijsw/angular-medium-editor#21]
Hi...@mbrevoort @thijsw 

This commit: 

https://github.com/thijsw/angular-medium-editor/commit/962d2e50785c8f6b18c20b5e25d9d2912de34ea7

From this pull request:

https://github.com/thijsw/angular-medium-editor/pull/5

Changed updating the model from watching just on('blur') to both on('blur') and on('input').

This has quite dramatically affected typing speed. (On on angular 1.2.24, Chrome 39.0.2171.42.)

I see the point of the change. But it does slow typing down a lot (i.e. there is a noticeable second or two pause after each key stroke).

(My usecase requires a a user to click a button after typing, so onBlur covers me.)

Feel free to close this issue if you'd like to keep onInput with the sluggishness.

**Comment by simison** [comment]
@michelob hi! Is this still relevant? The code has been refactored in between and for me this works great.

@thijsw Close? Sorry, I'm doing some issues maintaining here a bit. ;-)
