### ISSUE TITLE
Firefox giving alerts about obsolete keycodes

### ISSUE THREAD

**Issue by simison** [thijsw/angular-medium-editor#25]
KeyboardEvent.key value "Up" is obsolete and will be renamed to "ArrowUp". For more help https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.key

Same for "Right" (=>"ArrowRight"), "Esc" (=>"Escape") and so on.

**Comment by simonzack** [comment]
This happens whenever you access `event.key`, I don't think it can be avoided.

**Comment by simison** [comment]
Thanks. Just checking; these new `ArrowUp` etc will be working once they'll drop support for `Up`?
