### ISSUE TITLE
Bring up to date with latest medium editor release

### ISSUE THREAD

**Issue by benfoster** [thijsw/angular-medium-editor#31]
The main medium editor is now up to 3.0.9. Is this supported and if so can you bump the dependency version in the bower package?

**Comment by simison** [comment]
+1

**Comment by bubbleheadinc** [comment]
+1 Medium editor is now 4.2.0

**Comment by adrianorsouza** [comment]
+1

**Comment by julianfox** [comment]
+ 1

**Comment by thijsw** [comment]
I just updated the packages and created a new pre-release 0.1.0 of this package in commit 230ed4d. Can anyone who +1'ed this update take a moment to test this new version? I didn't see any issues, but could quite possibly missed something. Thanks in advance!

**Comment by simison** [comment]
Tested latest desktop Firefox+Safari+Chrome, both toolbar and single-line editor without toolbar.

Works perfect!

**Comment by adrianorsouza** [comment]
@thijsw I just tested it out, works flawlessly! Thanks for updates!

**Comment by simison** [comment]
BTW this won't work with mobile (tested some old iOS Safari) unlike old version, but that's a problem of Medium-editor, not this package.

If someone manages to get this work with this Angular version, lemme know: https://github.com/orthes/medium-editor-mobile-plugin

**Comment by simison** [comment]
https://github.com/thijsw/angular-medium-editor/pull/12 could still be tested.

**Comment by barryvdh** [comment]
In the meanwhile, you could test with `bower install medium-editor -F` to force the latest. Works for me :)
