### ISSUE TITLE
Placeholders are not replaced when model is erased programmatically 

### ISSUE THREAD

**Issue by simplesthing** [thijsw/angular-medium-editor#32]
In my controller I am resetting all fields in the ng-model to undefined but the placeholders are not getting replaced and the form then looks blank.

**Comment by simplesthing** [comment]
I was on v 0.6.0 upgraded to 0.1.0 and the problem is resolved

**Comment by simplesthing** [comment]
This was not actually resolved, here's a punkr http://plnkr.co/edit/BZq4Z10K6naGs3iZNZsA

Since I need this I'll be working on a PR to fix

**Comment by thijsw** [comment]
This is resolved with the upcoming 1.1.0 release
