### ISSUE TITLE
medium editor unless ng-model

### ISSUE THREAD

**Issue by cihad** [thijsw/angular-medium-editor#35]
I want to use only the medium editor. how can I use unless ng-model?

**Comment by darlanalves** [comment]
What's the point exactly? If you don't need a model to bind to the editor, you don't need the directive. You could use just the medium-editor library.

**Comment by simison** [comment]
@cihad check https://github.com/yabwe/medium-editor or perhaps Stackoverflow for generic questions.

@thijsw close?
