### ISSUE TITLE
Medium editor creates too many toolbars even when I go to another page

### ISSUE THREAD

**Issue by volyx** [thijsw/angular-medium-editor#37]
Medium editor don't destroy toolbar when i left page.

To repoduce - create many medium editors on page, more than 25 in my case.

![64fa8de41fc165d1c1471643b153eb83 1](https://cloud.githubusercontent.com/assets/3828802/8113508/251c78aa-1077-11e5-8a9d-d314b4c4bbaa.png)

**Comment by klmdb** [comment]
this could easily be fixed by adding

        scope.$on('$destroy', function() {
          ngModel.editor.destroy();
        });

to the link function.
