### ISSUE TITLE
Is this module still supported?

### ISSUE THREAD

**Issue by brazorf** [thijsw/angular-medium-editor#41]
Hey there
I've seen medium-editor supported version is 4.4.0, which dates on april 2015.
Since then, medium-editor upgraded branch 4 up to 4.12 and branch 5 up to 5.10

Should we consider angular-medium-editor fully supported still?

**Comment by simison** [comment]
See https://github.com/thijsw/angular-medium-editor/releases :-)

**Comment by brazorf** [comment]
Sorry bout this, but at the time i was posting last release was dated April.
Great to see it's well supported ;)
Cheers
