### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by bondneverdies** [thijsw/angular-medium-editor#48]
As no clear informations about any license could be found in the project repository, I would like to know which legal terms are applicable to your plugin ?

Please see http://www.gnu.org/licenses/license-list.en.html#NoLicense for a summary of the problems that no license would lead to.

**Comment by thijsw** [comment]
The license will be MIT. PR #45 includes this, I will merge that soon.

**Comment by bondneverdies** [comment]
Thanks for the clarification
