### ISSUE TITLE
NgModel appears to bind only 1 way.

### ISSUE THREAD

**Issue by Compulsed** [thijsw/angular-medium-editor#50]
When I attempt to change the ngModel programmatically within a controller, it seems to only bind one way so after I submit a form and try to set the ngModel to an empty string it is not reflected in the view.

Is there something I am missing or is this a general issue?

**Comment by simison** [comment]
Is that the case even if you do:

```
$timeout(function() {
  $scope.yourmodel = 'demo';
});
```

?

**Comment by Compulsed** [comment]
Thanks for taking the time to look at my issue.

I have tried that and most things similar to it, I read the source code and I am not sure that it supports doing something like

```
$scope.htmlModel = '<p>blah</p>';
```

It seems to me like the only way is to initially set it up with transclusion, then after that you cannot change th properties programmatically.

Please correct me if I am wrong.

**Comment by Compulsed** [comment]
I found the problem, I was applying the attribute directive to textarea tag rather than a div

**Comment by injectless** [comment]
can you share how you fix it?
