### ISSUE TITLE
Which buttons are supported?

### ISSUE THREAD

**Issue by EmileDMN** [thijsw/angular-medium-editor#51]
The original Medium editor provides the following list in built-in buttons available to use with the toolbar and editor: https://github.com/yabwe/medium-editor#all-buttons

However, only some of these seem to work with this directive. E.g. when appending ```'orderedlist'``` and ```'justifyCenter'``` to the array of buttons, the ordered list button appears and works fine but not for justify center, any idea why this is or if all the buttons are available?

**Comment by brazorf** [comment]
Which version of this plugin are you using, and which version of medium editor?
Can you paste a snippet of your configuration?

**Comment by EmileDMN** [comment]
Had just noticed this is probably the issue, just assumed we were using a recent version, my bad :)

**Comment by brazorf** [comment]
Can't say i'm aware of all the medium-editor releases, however the latest major (5) is supported since 1.1.0
