### ISSUE TITLE
Missing "main" key in`package.json` causes simple import failure

### ISSUE THREAD

**Issue by knigal** [thijsw/angular-medium-editor#74]
Unlike other packages, where the form
```js
import 'angular-medium-editor';
```
is sufficient to make `MediumEditor` available, this package requires the specific non-intuitive import form:
```js
import 'angular-medium-editor/dist/angular-medium-editor';
```
That's because in `package.json` there's no key such as:
```js
  "main": "dist/angular-medium-editor.js",
```
(this is done in many other packages)
* found on a Meteor (1.3)  project

**Comment by simison** [comment]
Good catch @knigal! I just added this.

@thijsw this would need a minor version bump to npm.
