### ISSUE TITLE
release

### ISSUE THREAD

**Issue by Twista** [thijsw/angular-medium-editor#75]
Hello,

would be possible to do a release ? we found that latest npm version is not working as intended due to #72 

thanks!

**Comment by thijsw** [comment]
No prob, hang on

**Comment by thijsw** [comment]
Just published release 1.2.1

**Comment by Twista** [comment]
awesome, thanks!

**Comment by Twista** [comment]
@thijsw in npm is still 1.1.1 (see https://www.npmjs.com/package/angular-medium-editor)

isn't necessary to run `npm publish` again ?

**Comment by thijsw** [comment]
Updated!
