### ISSUE TITLE
allow a model change function to be passed

### ISSUE THREAD

**Issue by mattgi** [thijsw/angular-medium-editor#8]
ng-change is apparently not supported in non-input elements so there is no way to hook in to updates to the editor so that data can be updated server-side. How is this achieved?

I have played with passing a call to the controller's method by adding an attr in to the directive to accept the function - something like `medium-editor model-change="saveSection()"`. In the directive I then added:

```
ctrl.$viewChangeListeners.push(function() {
   scope.$eval(iAttrs.modelChange);
});
```

Whilst things fire as expected it doesn't work how I thought it would - the model updates too often and removes whatever has just been changed.

Any ideas?

**Comment by darlanalves** [comment]
Same here SeveQ. Works just fine with ng-model and ng-change on a <P> tag.
